Fiap05.Web.MVC/Fiap05.Web.MVC/Models/Autor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap05.Web.MVC.Models
{
    public class Autor
    {
        public int AutorId { get; set; }
        public string Nome { get; set; }
        public string Genero { get; set; }
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Models/Livro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap05.Web.MVC.Models
{
    public class Livro
    {       
        public int LivroId { get; set; }

        [Required]
        public string Titulo { get; set; }

        public DateTime DataCadastro { get; set; }

        public bool Disponivel { get; set; }
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap05.Web.MVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Controllers/LivroController.cs
using Fiap05.Web.MVC.Models;
using Fiap05.Web.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap05.Web.MVC.Controllers
{
    public class LivroController : Controller
    {
        private BibliotecaContext _context = new BibliotecaContext();

        [HttpGet]
        public ActionResult Buscar(string tituloBusca)
        {
            //Buscar os livros no banco de dados pelo título
            var lista = _context.Livros.Where(t => t.Titulo.Contains(tituloBusca)).ToList();
            //retornar a página com os livros
            return View("Listar",lista);
        }

        [HttpPost]
        public ActionResult Excluir(int id)
        {
            //Busca o livro
            var livro = _context.Livros.Find(id);
            //Remover o livro
            _context.Livros.Remove(livro);
            _context.SaveChanges();
            TempData["msg"] = "Livro removido!";
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Editar(Livro livro)
        {
            //Atualiza no banco de dados
            _context.Entry(livro).State = EntityState.Modified;
            _context.SaveChanges();
            //mensagem
            TempData["msg"] = "Livro atualizado!";
            //redirect
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            var livro = _context.Livros.Find(id);
            return View(livro);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            //Busca os livros no banco de dados
            var lista = _context.Livros.ToList();
            //Retorna a página com a lista de livros
            return View(lista);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Livro livro)
        {
            _context.Livros.Add(livro);
            _context.SaveChanges();
            TempData["msg"] = "Livro cadastrado!";
            return RedirectToAction("Cadastrar");
        }
    }
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Views/Livro/Cadastrar.cshtml
@model Fiap05.Web.MVC.Models.Livro

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Livro</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(a => a.Titulo)
        @Html.TextBoxFor(a => a.Titulo, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.DataCadastro)
        @Html.TextBoxFor(a => a.DataCadastro, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(a => a.Disponivel)
        @Html.LabelFor(a => a.Disponivel)
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Views/Livro/Editar.cshtml
@model Fiap05.Web.MVC.Models.Livro

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(l => l.LivroId)
    <div class="form-group">
        @Html.LabelFor(l => l.Titulo)
        @Html.TextBoxFor(l => l.Titulo, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(l => l.DataCadastro)
        @Html.TextBoxFor(l => l.DataCadastro, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(l => l.Disponivel)
        @Html.LabelFor(l => l.Disponivel)
    </div>
    <input type="submit" value="Editar" class="btn btn-primary" />
}

Fiap05.Web.MVC/Fiap05.Web.MVC/Views/Livro/Listar.cshtml
@model List<Fiap05.Web.MVC.Models.Livro>
@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm("Buscar","Livro",FormMethod.Get, new { @class = "form-inline" }))
{
    <input type="search" name="tituloBusca" placeholder="Digite um título" class="form-control" />
    <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-search"></span>
    </button>
}
<br />

@if (!Model.Any())
{
    <p>Sem resultados</p>
}

<table class="table table-striped">
    <tr>
        <th>Código</th>
        <th>Título</th>
        <th>Data Cadastro</th>
        <th>Disponível</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.LivroId</td>
            <td>@item.Titulo</td>
            <td>@item.DataCadastro</td>
            <td>@item.Disponivel</td>
            <td>
                @Html.ActionLink("Alterar", "Editar", new { id = item.LivroId },
                    new { @class = "btn btn-info btn-xs" })
                <!-- Button trigger modal -->
                <button onclick="codigoLivro.value = @item.LivroId" type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#myModal">
                    Remover
                </button>
            </td>
        </tr>
    }
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
            </div>
            <div class="modal-body">
                Tem certeza que você deseja apagar o livro?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Excluir", "Livro"))
                {
                    <input type="hidden" name="id" id="codigoLivro" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-danger">Excluir</button>
                }
            </div>
        </div>
    </div>
</div>

Fiap05.Web.MVC/Fiap05.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Biblioteca", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro de Livro","Cadastrar","Livro")</li>
                    <li>@Html.ActionLink("Livros","Listar","Livro")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>