Fiap06.Web.MVC/Fiap06.Web.MVC/Models/Campeonato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap06.Web.MVC.Models
{
    public class Campeonato
    {
        public int CampeonatoId { get; set; }
        public string Nome { get; set; }
        public int Rodadas { get; set; }

        //Relacionamentos
        public IList<Time> Times { get; set; }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Models/Jogador.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap06.Web.MVC.Models
{
    public class Jogador
    {
        public int JogadorId { get; set; }
        public string Nome { get; set; }
        public DateTime DataNascimento { get; set; }

        public Posicao? Posicao { get; set; }

        //Relacionamentos
        public Time Time { get; set; }
        public int TimeId { get; set; }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Models/Posicao.cs
namespace Fiap06.Web.MVC.Models
{
    public enum Posicao
    {
        Goleiro, Lateral, Zagueiro, Meia, Atacante
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Models/Treinador.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap06.Web.MVC.Models
{
    public class Treinador
    {
        public int TreinadorId { get; set; }
        public string Nome { get; set; }
        public decimal Salario { get; set; }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Models/time.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap06.Web.MVC.Models
{
    public class Time
    {
        public int TimeId { get; set; }
        public string Nome { get; set; }
        public long Torcedores { get; set; }

        //Relacionamentos
        public Treinador Treinador { get; set; }
        public int? TreinadorId { get; set; }

        public IList<Jogador> Jogadores { get; set; }

        public IList<Campeonato> Campeonatos { get; set; }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Controllers/JogadorController.cs
using Fiap06.Web.MVC.Models;
using Fiap06.Web.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap06.Web.MVC.Controllers
{
    public class JogadorController : Controller
    {
        private FutebolContext _context = new FutebolContext();

        [HttpGet]
        public ActionResult Buscar(int? time)
        {
            var lista = _context.Jogadores.Include("Time")
                .Where(j => j.TimeId == time || time == null).ToList();
            CarregarComboTimes();
            return View("Listar", lista);
        }

        private void CarregarComboTimes()
        {
            //Enviar os times para o drowpdown
            var times = _context.Times.ToList();
            ViewBag.times = new SelectList(times, "TimeId", "Nome");
        }

        [HttpGet]
        public ActionResult Listar()
        {
            CarregarComboTimes();
            //Include -> inclui a relação do jogador com o time na busca
            var lista = _context.Jogadores.Include("Time").ToList();
            return View(lista);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            //Buscar todos os times cadastrados
            var lista = _context.Times.ToList();
            //Passar a lista para a tela
            ViewBag.times = new SelectList(lista, "TimeId", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Jogador jogador)
        {
            _context.Jogadores.Add(jogador);
            _context.SaveChanges();
            TempData["msg"] = "Jogador cadastrado";
            return RedirectToAction("Cadastrar");
        }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Controllers/TimeController.cs
using Fiap06.Web.MVC.Models;
using Fiap06.Web.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap06.Web.MVC.Controllers
{
    public class TimeController : Controller
    {
        private FutebolContext _context = new FutebolContext();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Time time)
        {
            _context.Times.Add(time);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado com sucesso";
            return RedirectToAction("Cadastrar");
        }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Time <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastrar", "Cadastrar", "Time")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Jogador <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastrar","Cadastrar","Jogador")</li>
                            <li>@Html.ActionLink("Jogadores","Listar","Jogador")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Time/Cadastrar.cshtml
@model Fiap06.Web.MVC.Models.Time

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Time</h2>
@Ajudante.Mensagem(TempData["msg"])

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(t => t.Nome)
        @Html.TextBoxFor(t => t.Nome, new { @class= "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(t => t.Torcedores)
        @Html.TextBoxFor(t => t.Torcedores, new { @class = "form-control"})
    </div>
    <fieldset>
        <legend>Técnico</legend>
        <div class="form-group">
            @Html.LabelFor(t => t.Treinador.Nome)
            @Html.TextBoxFor(t => t.Treinador.Nome, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(t => t.Treinador.Salario)
            @Html.TextBoxFor(t => t.Treinador.Salario, new { @class = "form-control" })
        </div>
    </fieldset>
    @Ajudante.Botao("Cadastrar")
}